<h1>User Administration</h1>
<?php if ($this->users): ?>
	<table class="table">
		<thead>
			<tr>
				<th>userId</th>
				<th>firstName</th>
				<th>lastName</th>
				<th>email</th>
				<th>password</th>
				<th>dateCreated</th>
				<th>dateLoggeddIn</th>
			</tr>
		</thead>
		<tbody>
		<?php foreach ($this->users as $user): ?>
			<tr>
				<td><?php echo $user->userId; ?></td>
				<td><?php echo $user->firstName; ?></td>
				<td><?php echo $user->lastName; ?></td>
				<td><?php echo $user->email; ?></td>
				<td><?php echo $user->password; ?></td>
				<td><?php echo $user->dateCreated; ?></td>
				<td><?php echo $user->dateLoggedIn; ?></td>
			</tr>
		<?php endforeach; ?>
		</tbody>
	</table>
<?php endif; ?>