<div class="navbar navbar-inverse navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</a>
        
			<a class="brand" href="<?php echo $this->url(array('module' => 'default', 'controller' => 'index', 'action' => 'index'), 'default', true); ?>">Hobbies and Clubs.co.uk</a>
          
          	<div class=" nav-collapse collapse">
	          	<ul class="nav">
					<li class="active"><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'index', 'action' => 'index'), 'default', true); ?>">Home</a></li>
					<?php if (Zend_Auth::getInstance()->hasIdentity()): ?>
						<li><a href="<?php echo $this->url(array('module' => 'club', 'controller' => 'manage', 'action' => 'index'), 'default', true); ?>">My Groups</a></li>
						<li><a href="<?php echo $this->url(array('module' => 'user', 'controller' => 'auth', 'action' => 'logout'), 'default', true); ?>">Log out</a></li>
					<?php else: ?>
						<li><a href="<?php echo $this->url(array('module' => 'user', 'controller' => 'registration', 'action' => 'index'), 'default', true); ?>">Register</a></li>
						<li><a href="<?php echo $this->url(array('module' => 'user', 'controller' => 'auth', 'action' => 'login'), 'default', true); ?>">Log in</a></li>
					<?php endif; ?>
				</ul>
          	</div>
          	
          	<form class="navbar-search pull-right" action="">
				<input type="text" class="search-query span2" placeholder="Search">
			</form>
          	
		</div>
	</div>
</div>