<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Hobbies and Clubs.co.uk');
echo $this->doctype(); ?>
<head>
    <?php echo $this->headMeta(); ?>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?php echo $this->headTitle(); ?>
    <?php echo $this->headLink()->appendStylesheet($this->baseUrl().'/css/bootstrap.css')
                                 ->appendStylesheet($this->baseUrl().'/css/bootstrap-responsive.css'); ?>
	<?php echo $this->headScript()->appendFile("//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js")
								   ->appendFile("//ajax.googleapis.com/ajax/libs/jqueryui/1.10.2/jquery-ui.min.js")
								   ->appendFile($this->baseUrl().'/js/bootstrap.js'); ?>
    
    <meta charset="utf-8">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

	<style type="text/css">
	  html, body {
        background-color: #eee;
      }
      .container > footer p {
        text-align: center; /* center align it with the container */
      }
      .container {
        width: 820px; /* downsize our container to make the content feel a bit tighter and more cohesive. NOTE: this removes two full columns from the grid, meaning you only go to 14 columns and not 16. */
      }
      
      .container-fluid {
      	max-width: 820px;
        margin: 0 auto;
      }

      /* The white background content wrapper */
      .content {
        background-color: #fff;
        padding: 20px;
        margin: 0 -20px; /* negative indent the amount of the padding to maintain the grid system */
        -webkit-border-radius: 0 0 6px 6px;
           -moz-border-radius: 0 0 6px 6px;
                border-radius: 0 0 6px 6px;
        -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.15);
           -moz-box-shadow: 0 1px 2px rgba(0,0,0,.15);
                box-shadow: 0 1px 2px rgba(0,0,0,.15);
      }

      /* Page header tweaks */
      .page-header {
        background-color: #f5f5f5;
        padding: 20px 20px 10px;
        margin: -20px -20px 20px;
      }
		</style>
</head>
<body>

<?php echo $this->partial('partials/navigation.phtml', array('sitesearch' => $this->sitesearch)); ?>

<div id="content">
    <div class="container-fluid">
      <div class="content">
        <div class="page-header">
          <h1><?php echo $this->escape($this->title); ?></h1>
        </div>
        
        <?php echo $this->flash() ?>
    
    	<?php echo $this->layout()->content; ?>
    	
      </div>

      <footer>
      Footer Content here.
      </footer>

    </div> <!-- /container -->
</div>
</body>
</html>